AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1 # increase the epochs whenever you trained your model
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01